#![allow(clippy::cast_possible_wrap)] // u32→c_int for FFI
#![allow(clippy::missing_panics_doc)] // functions panic on lock() failure
//! Compiled C test utilities for the zfp-rs integration test suite.
//!
//! Exposes safe wrappers around `generateSmoothRandNums` from the upstream
//! ZFP test suite, which produces smooth random arrays that are byte-identical
//! to those generated by the C tests.  Used by `tests/c/endtoend.rs`.

use libc::c_int;
use std::sync::Mutex;

unsafe extern "C" {
    fn generateSmoothRandInts64(
        min_total_elements: usize,
        num_dims: c_int,
        amplitude_exp: c_int,
        output_arr: *mut *mut i64,
        output_side_len: *mut usize,
        output_total_len: *mut usize,
    );

    fn generateSmoothRandInts32(
        min_total_elements: usize,
        num_dims: c_int,
        amplitude_exp: c_int,
        output_arr: *mut *mut i32,
        output_side_len: *mut usize,
        output_total_len: *mut usize,
    );

    fn generateSmoothRandFloats(
        min_total_elements: usize,
        num_dims: c_int,
        output_arr: *mut *mut f32,
        output_side_len: *mut usize,
        output_total_len: *mut usize,
    );

    fn generateSmoothRandDoubles(
        min_total_elements: usize,
        num_dims: c_int,
        output_arr: *mut *mut f64,
        output_side_len: *mut usize,
        output_total_len: *mut usize,
    );
}

// ---------------------------------------------------------------------------
// Global mutex serialising all calls to the C generators.
//
// The upstream C utilities use a single process-wide static RNG (`X` in
// `rand64.c`).  Each generator calls `resetRandGen()` before producing
// output, so concurrent calls from different threads would corrupt each
// other's state and yield wrong (or non-deterministic) arrays.
// Holding this mutex for the duration of each FFI call makes the wrappers
// safe to call from any number of threads simultaneously.
// ---------------------------------------------------------------------------
static RAND_GEN_LOCK: Mutex<()> = Mutex::new(());

// ---------------------------------------------------------------------------
// RAII wrapper for C malloc'd arrays
// ---------------------------------------------------------------------------

struct CMallocVec<T> {
    ptr: *mut T,
    len: usize,
}

impl<T> CMallocVec<T> {
    /// # Safety
    /// `ptr` must be a valid, non-null pointer to a C-malloc'd array of `len` elements of type `T`.
    unsafe fn from_raw(ptr: *mut T, len: usize) -> Self {
        assert!(!ptr.is_null(), "C generator returned null pointer");
        CMallocVec { ptr, len }
    }

    fn as_slice(&self) -> &[T] {
        // SAFETY: ptr is a valid, non-null C malloc'd array of `len` elements.
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }
}

impl<T> Drop for CMallocVec<T> {
    fn drop(&mut self) {
        // SAFETY: ptr was obtained from C malloc and has not been freed yet.
        unsafe { libc::free(self.ptr.cast::<libc::c_void>()) }
    }
}

// ---------------------------------------------------------------------------
// Public API: returns owned Vec<T> copies, freeing the C allocation
// ---------------------------------------------------------------------------

/// Generate a smooth random `i32` array of at least 4096 elements in `dims` dimensions.
/// Returns `(data, side_len, total_len)` where the array is square (`side_len^dims` elements).
pub fn gen_smooth_rand_ints32(dims: u32) -> (Vec<i32>, usize, usize) {
    let _guard = RAND_GEN_LOCK.lock().unwrap();
    let (mut ptr, mut side, mut total) = (std::ptr::null_mut(), 0usize, 0usize);
    // SAFETY: FFI call; out-parameters are initialised by callee.
    unsafe {
        generateSmoothRandInts32(
            4096,
            dims as c_int,
            30,
            &raw mut ptr,
            &raw mut side,
            &raw mut total,
        );
        let cdata = CMallocVec::from_raw(ptr, total);
        (cdata.as_slice().to_vec(), side, total)
    }
}

/// Generate a smooth random `i64` array of at least 4096 elements in `dims` dimensions.
pub fn gen_smooth_rand_ints64(dims: u32) -> (Vec<i64>, usize, usize) {
    let _guard = RAND_GEN_LOCK.lock().unwrap();
    let (mut ptr, mut side, mut total) = (std::ptr::null_mut(), 0usize, 0usize);
    // SAFETY: FFI call; out-parameters are initialised by callee.
    unsafe {
        generateSmoothRandInts64(
            4096,
            dims as c_int,
            62,
            &raw mut ptr,
            &raw mut side,
            &raw mut total,
        );
        let cdata = CMallocVec::from_raw(ptr, total);
        (cdata.as_slice().to_vec(), side, total)
    }
}

/// Generate a smooth random `f32` array of at least 1 000 000 elements in `dims` dimensions.
pub fn gen_smooth_rand_floats(dims: u32) -> (Vec<f32>, usize, usize) {
    let _guard = RAND_GEN_LOCK.lock().unwrap();
    let (mut ptr, mut side, mut total) = (std::ptr::null_mut(), 0usize, 0usize);
    // SAFETY: FFI call; out-parameters are initialised by callee.
    unsafe {
        generateSmoothRandFloats(
            1_000_000,
            dims as c_int,
            &raw mut ptr,
            &raw mut side,
            &raw mut total,
        );
        let cdata = CMallocVec::from_raw(ptr, total);
        (cdata.as_slice().to_vec(), side, total)
    }
}

/// Generate a smooth random `f64` array of at least 1 000 000 elements in `dims` dimensions.
pub fn gen_smooth_rand_doubles(dims: u32) -> (Vec<f64>, usize, usize) {
    let _guard = RAND_GEN_LOCK.lock().unwrap();
    let (mut ptr, mut side, mut total) = (std::ptr::null_mut(), 0usize, 0usize);
    // SAFETY: FFI call; out-parameters are initialised by callee.
    unsafe {
        generateSmoothRandDoubles(
            1_000_000,
            dims as c_int,
            &raw mut ptr,
            &raw mut side,
            &raw mut total,
        );
        let cdata = CMallocVec::from_raw(ptr, total);
        (cdata.as_slice().to_vec(), side, total)
    }
}
