#ifndef ZFP_RS_FFI_H
#define ZFP_RS_FFI_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#define ZFP_VERSION_MAJOR 1
#define ZFP_VERSION_MINOR 0
#define ZFP_VERSION_PATCH 1
#define ZFP_VERSION_TWEAK 0
#define ZFP_VERSION_DEVELOP 1
#define ZFP_CODEC 5

#define ZFP_MAKE_VERSION(major, minor, patch, tweak) \
  (((major) << 12) + ((minor) << 8) + ((patch) << 4) + ((tweak) << 0))
#define ZFP_VERSION \
  ZFP_MAKE_VERSION(ZFP_VERSION_MAJOR, ZFP_VERSION_MINOR, ZFP_VERSION_PATCH, ZFP_VERSION_TWEAK)
#define ZFP_VERSION_STRING "1.0.1"

#define ZFP_MIN_BITS 1
#define ZFP_MAX_BITS 16658
#define ZFP_MAX_PREC 64
#define ZFP_MIN_EXP -1074

#define ZFP_HEADER_NONE 0x0u
#define ZFP_HEADER_MAGIC 0x1u
#define ZFP_HEADER_META 0x2u
#define ZFP_HEADER_MODE 0x4u
#define ZFP_HEADER_FULL 0x7u

#define ZFP_DATA_UNUSED 0x01u
#define ZFP_DATA_PADDING 0x02u
#define ZFP_DATA_META 0x04u
#define ZFP_DATA_MISC 0x08u
#define ZFP_DATA_PAYLOAD 0x10u
#define ZFP_DATA_INDEX 0x20u
#define ZFP_DATA_CACHE 0x40u
#define ZFP_DATA_HEADER 0x80u
#define ZFP_DATA_ALL 0xffu

#define ZFP_META_NULL UINT64_MAX
#define ZFP_MAGIC_BITS 32
#define ZFP_META_BITS 52
#define ZFP_MODE_SHORT_BITS 12
#define ZFP_MODE_LONG_BITS 64
#define ZFP_HEADER_MAX_BITS 148
#define ZFP_MODE_SHORT_MAX ((1u << ZFP_MODE_SHORT_BITS) - 2)

#define ZFP_ROUND_FIRST (-1)
#define ZFP_ROUND_NEVER 0
#define ZFP_ROUND_LAST 1

enum {
  zfp_false = 0,
  zfp_true = !zfp_false
};

typedef struct bitstream bitstream;
typedef int8_t int8;
typedef uint8_t uint8;
typedef int16_t int16;
typedef uint16_t uint16;
typedef int32_t int32;
typedef int64_t int64;



typedef enum zfp_exec_policy {
  zfp_exec_serial = 0,
  zfp_exec_omp = 1,
  zfp_exec_cuda = 2,
} zfp_exec_policy;

typedef enum zfp_mode {
  zfp_mode_null = 0,
  zfp_mode_expert = 1,
  zfp_mode_fixed_rate = 2,
  zfp_mode_fixed_precision = 3,
  zfp_mode_fixed_accuracy = 4,
  zfp_mode_reversible = 5,
} zfp_mode;

typedef enum zfp_type {
  zfp_type_none = 0,
  zfp_type_int32 = 1,
  zfp_type_int64 = 2,
  zfp_type_float = 3,
  zfp_type_double = 4,
} zfp_type;

typedef size_t bitstream_count;

typedef uint32_t uint;

typedef uint64_t uint64;

typedef uint64 bitstream_offset;

typedef bitstream_offset bitstream_size;

typedef struct zfp_field {
  enum zfp_type type;
  size_t nx;
  size_t ny;
  size_t nz;
  size_t nw;
  ptrdiff_t sx;
  ptrdiff_t sy;
  ptrdiff_t sz;
  ptrdiff_t sw;
  void *data;
} zfp_field;

typedef int32_t zfp_bool;

typedef struct zfp_config__bindgen_ty_1__bindgen_ty_1 {
  uint minbits;
  uint maxbits;
  uint maxprec;
  int32_t minexp;
} zfp_config__bindgen_ty_1__bindgen_ty_1;

typedef union zfp_config__bindgen_ty_1 {
  double rate;
  uint precision;
  double tolerance;
  struct zfp_config__bindgen_ty_1__bindgen_ty_1 expert;
} zfp_config__bindgen_ty_1;

typedef struct zfp_config {
  enum zfp_mode mode;
  union zfp_config__bindgen_ty_1 arg;
} zfp_config;

typedef struct zfp_execution {
  enum zfp_exec_policy policy;
  void *params;
} zfp_execution;

typedef struct zfp_stream {
  uint minbits;
  uint maxbits;
  uint maxprec;
  int32_t minexp;
  bitstream *stream;
  struct zfp_execution exec;
} zfp_stream;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const size_t stream_word_bits;

extern const uint32_t zfp_codec_version;

extern const uint32_t zfp_library_version;

bitstream *stream_open(void *buffer, size_t bytes);

void stream_close(bitstream *stream);

bitstream *stream_clone(const bitstream *stream);

bitstream_count stream_alignment(void);

void *stream_data(const bitstream *stream);

size_t stream_size(const bitstream *stream);

size_t stream_capacity(const bitstream *stream);

size_t stream_stride_block(const bitstream *_stream);

ptrdiff_t stream_stride_delta(const bitstream *_stream);

uint stream_read_bit(bitstream *stream);

uint stream_write_bit(bitstream *stream, uint bit);

uint64 stream_read_bits(bitstream *stream, bitstream_count n);

uint64 stream_write_bits(bitstream *stream, uint64 value, bitstream_count n);

bitstream_offset stream_rtell(const bitstream *stream);

bitstream_offset stream_wtell(const bitstream *stream);

void stream_rewind(bitstream *stream);

void stream_rseek(bitstream *stream, bitstream_offset offset);

void stream_wseek(bitstream *stream, bitstream_offset offset);

void stream_skip(bitstream *stream, bitstream_size n);

void stream_pad(bitstream *stream, bitstream_size n);

bitstream_count stream_align(bitstream *stream);

bitstream_count stream_flush(bitstream *stream);

void stream_copy(bitstream *dst, bitstream *src, bitstream_size n);

struct zfp_field *zfp_field_alloc(void);

struct zfp_field *zfp_field_1d(void *data, enum zfp_type scalar_type, size_t nx);

struct zfp_field *zfp_field_2d(void *data, enum zfp_type scalar_type, size_t nx, size_t ny);

struct zfp_field *zfp_field_3d(void *data,
                               enum zfp_type scalar_type,
                               size_t nx,
                               size_t ny,
                               size_t nz);

struct zfp_field *zfp_field_4d(void *data,
                               enum zfp_type scalar_type,
                               size_t nx,
                               size_t ny,
                               size_t nz,
                               size_t nw);

void zfp_field_free(struct zfp_field *field);

void *zfp_field_pointer(const struct zfp_field *field);

void *zfp_field_begin(const struct zfp_field *field);

enum zfp_type zfp_field_type(const struct zfp_field *field);

uint zfp_field_precision(const struct zfp_field *field);

uint zfp_field_dimensionality(const struct zfp_field *field);

size_t zfp_field_size(const struct zfp_field *field, size_t *dims);

size_t zfp_field_size_bytes(const struct zfp_field *field);

size_t zfp_field_blocks(const struct zfp_field *field);

zfp_bool zfp_field_stride(const struct zfp_field *field, ptrdiff_t *strides);

zfp_bool zfp_field_is_contiguous(const struct zfp_field *field);

uint64 zfp_field_metadata(const struct zfp_field *field);

void zfp_field_set_pointer(struct zfp_field *field, void *ptr);

enum zfp_type zfp_field_set_type(struct zfp_field *field, enum zfp_type ty);

void zfp_field_set_size_1d(struct zfp_field *field, size_t nx);

void zfp_field_set_size_2d(struct zfp_field *field, size_t nx, size_t ny);

void zfp_field_set_size_3d(struct zfp_field *field, size_t nx, size_t ny, size_t nz);

void zfp_field_set_size_4d(struct zfp_field *field, size_t nx, size_t ny, size_t nz, size_t nw);

void zfp_field_set_stride_1d(struct zfp_field *field, ptrdiff_t sx);

void zfp_field_set_stride_2d(struct zfp_field *field, ptrdiff_t sx, ptrdiff_t sy);

void zfp_field_set_stride_3d(struct zfp_field *field, ptrdiff_t sx, ptrdiff_t sy, ptrdiff_t sz);

void zfp_field_set_stride_4d(struct zfp_field *field,
                             ptrdiff_t sx,
                             ptrdiff_t sy,
                             ptrdiff_t sz,
                             ptrdiff_t sw);

zfp_bool zfp_field_set_metadata(struct zfp_field *field, uint64 metadata);

struct zfp_config zfp_config_none(void);

struct zfp_config zfp_config_rate(double rate, zfp_bool align);

struct zfp_config zfp_config_precision(uint32_t precision);

struct zfp_config zfp_config_accuracy(double tolerance);

struct zfp_config zfp_config_reversible(void);

struct zfp_config zfp_config_expert(uint32_t minbits,
                                    uint32_t maxbits,
                                    uint32_t maxprec,
                                    int32_t minexp);

size_t zfp_type_size(enum zfp_type ty);

struct zfp_stream *zfp_stream_open(bitstream *bs);

void zfp_stream_close(struct zfp_stream *stream);

bitstream *zfp_stream_bit_stream(const struct zfp_stream *stream);

enum zfp_mode zfp_stream_compression_mode(const struct zfp_stream *stream);

double zfp_stream_rate(const struct zfp_stream *stream, uint dims);

uint zfp_stream_precision(const struct zfp_stream *stream);

double zfp_stream_accuracy(const struct zfp_stream *stream);

uint64 zfp_stream_mode(const struct zfp_stream *stream);

void zfp_stream_params(const struct zfp_stream *stream,
                       uint *minbits,
                       uint *maxbits,
                       uint *maxprec,
                       int32_t *minexp);

size_t zfp_stream_compressed_size(const struct zfp_stream *stream);

size_t zfp_stream_maximum_size(const struct zfp_stream *stream, const struct zfp_field *field);

size_t zfp_write_header(struct zfp_stream *stream, const struct zfp_field *field, uint mask);

size_t zfp_read_header(struct zfp_stream *stream, struct zfp_field *field, uint mask);

size_t zfp_compress(struct zfp_stream *stream, const struct zfp_field *field);

size_t zfp_decompress(struct zfp_stream *stream, struct zfp_field *field);

void zfp_stream_rewind(struct zfp_stream *stream);

void zfp_stream_set_bit_stream(struct zfp_stream *stream, bitstream *bs);

void zfp_stream_set_reversible(struct zfp_stream *stream);

double zfp_stream_set_rate(struct zfp_stream *stream,
                           double rate,
                           enum zfp_type ty,
                           uint dims,
                           zfp_bool align);

uint zfp_stream_set_precision(struct zfp_stream *stream, uint precision);

double zfp_stream_set_accuracy(struct zfp_stream *stream, double tolerance);

enum zfp_mode zfp_stream_set_mode(struct zfp_stream *stream, uint64 mode);

zfp_bool zfp_stream_set_params(struct zfp_stream *stream,
                               uint minbits,
                               uint maxbits,
                               uint maxprec,
                               int32_t minexp);

enum zfp_exec_policy zfp_stream_execution(const struct zfp_stream *stream);

uint zfp_stream_omp_threads(const struct zfp_stream *stream);

uint zfp_stream_omp_chunk_size(const struct zfp_stream *stream);

zfp_bool zfp_stream_set_execution(struct zfp_stream *stream, enum zfp_exec_policy policy);

zfp_bool zfp_stream_set_omp_threads(struct zfp_stream *stream, uint threads);

zfp_bool zfp_stream_set_omp_chunk_size(struct zfp_stream *stream, uint chunk_size);

size_t zfp_stream_flush(struct zfp_stream *stream);

size_t zfp_stream_align(struct zfp_stream *stream);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ZFP_RS_FFI_H */
